server:
  port: 2121
ies:
  properties:
    message: welcome to IES-dev
    success: Registration Sucessful
    failed: Registration failed
    regEmailFileName: Registration_Email_Template.txt
    regEmailSubject: IES Registration Completed
    planCreatedSuccess: Plan Created Sucessfully
    planCreationFailue: Plan Creation Failed please enter valid inputs
    planActivationSuccess: Plan is Activated
    planActivationFailed: Plan is not Activated 
    planDeletedSuccess: Plan is De-Activated
    planDeletedFailed: plan is not De-Activated
    loginSuccess: success
    loginFailedInvalidCredentials: Invalid credentials...
    loginFailedDeActivated: Account is De-Activated...
    pwdRecoverySubject: IES login Details
    pwdRecoveryFileName: PasswordRecovery_Email_Template.txt
    pwdRecoveryEmailSubject: IES Account Detials
    pwdRecoverySuccess: Password Sucessfully recovered.. please check your email for Account Details
    pwdRecoveryFailure: Password Recovery failed 
logging:
  file: IES-APP-LOGS.log
  level:
    root: INFO
    com.usa.ri.gov.ies: DEBUG
spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true   
        dialect:    org.hibernate.dialect.Oracle10gDialect     #org.hibernate.dialect.MySQL5Dialect
  datasource:
    username: system
    password: pulla143
    url: jdbc:oracle:thin:@localhost:1521:xe
    driver-class-name: oracle.jdbc.driver.OracleDriver
  #  url: jdbc:mysql://localhost:3306/sodam
   # username: root
  #  password: pULLA143
 #   driver-class-name: com.mysql.jdbc.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: pullareddy970@gmail.com
    password: mail$143
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true