server:
  port: 2121

#Propertis of Application
ies:
  properties:
    message: welcome to IES-dev
    success: Registration Sucessful
    failed: Registration failed
    regEmailFileName: Registration_Email_Template.txt
    regEmailSubject: IES Registration Completed
    accEditMailSubject: IES Account Detils Updated
    accEditMailTemplateFile: Account_Edit_Email_Template.txt
    accEditSuccess: Account details are successully edited
    accEditFailed: Account details edit failed
    appAccountActivationSuccess: Account is Activated
    appAccountActivationFailed: Account is not Activated 
    appAccountDeletedSuccess: Account is De-Activated
    appAccountDeletedFailed: Account is not De-Activated
    planCreatedSuccess: Plan Created Sucessfully
    planCreationFailue: Plan Creation Failed please enter valid inputs
    planAccEditSuccess: Plan account details are successully updated
    planAccEditFailed:   Plan account details update failed
    planActivationSuccess: Plan is Activated
    planActivationFailed: Plan is not Activated 
    planDeletedSuccess: Plan is De-Activated
    planDeletedFailed: plan is not De-Activated
    loginSuccess: success
    loginFailedInvalidCredentials: Invalid credentials...
    loginFailedDeActivated: Account isS De-Activated...
    pwdRecoverySubject: IES Account Recovered
    pwdRecoveryFileName: PasswordRecovery_Email_Template.txt
    pwdRecoveryEmailSubject: IES Account Detials
    pwdRecoveryFailure: Password Recovery failed 
    pwdRecoveryFailed: Enter valid registred email
    pwdRecoverySuccess: Password is successfully recovered please check your mail
    registrationSuccess: Application Registrataion Successful
    registrationFailed: Application Registrattion failed
    invalidSSNMsg: Invalide SSN Provided!!
    unAuthorisedApplicant: "Un-Authorised Applicant to Apply for Plan"
    applicantRegSuccess: Applicant Registered Successfully with AppId 
    applicantAlreadyReg: Applicant Already Registered with AppId 
    internalProblem: Internal Problem Contact Admin
#logging configuration
logging:
  file: IES-APP-LOGS.log
  level:
    root: INFO
    com.usa.ri.gov.ies: DEBUG
    
 #Spring 
spring:
  #database configuration
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true   
        dialect:  org.hibernate.dialect.Oracle10gDialect        #org.hibernate.dialect.MySQL5Dialect org.hibernate.dialect.Oracle10gDialect 
  datasource:
    username: system
    password: pulla143
    url: jdbc:oracle:thin:@localhost:1521:xe
    driver-class-name: oracle.jdbc.driver.OracleDriver
#    url: jdbc:mysql://localhost:3306/sodam
#    username: root
#    password: pULLA143
#    driver-class-name: com.mysql.jdbc.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: pullareddy970@gmail.com
    password: mail$143
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true