
server:
  port: 7070
  
ies:
  properties:
      message: welcome to IES-dev 
      success: Registration Sucessful
      failed: Registration failed
logging:
  file: IES-APP-LOGS.log
  level:
    com.usa.ri.gov.ies: info 
   
spring:
  jpa:
    hibernate:
      ddl-auto: update
      
    show-sql: true
    
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: system
    password: pulla143