server:
  port: 2121
ies:
  properties:
    message: welcome to IES-dev
    success: Registration Sucessful
    failed: Registration failed
    regEmailFileName: Registration_Email_Template.txt
    regEmailSubject: IES Registration Completed
logging:
  file: IES-APP-LOGS.log
  level:
    root: INFO
    com.usa.ri.gov.ies: DEBUG
spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true   
        dialect: org.hibernate.dialect.Oracle10gDialect #org.hibernate.dialect.MySQL5Dialect
  datasource:
    username: system
    password: manager
    url: jdbc:oracle:thin:@localhost:1521:xe
    driver-class-name: oracle.jdbc.driver.OracleDriver
#    url: jdbc:mysql://localhost:3306/sodam
#    username: root
#    password: pULLA143
#    driver-class-name: com.mysql.jdbc.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: pullareddy970@gmail.com
    password: xxxxx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true